export const movies = [
  // Walt Disney Animation Studios — released feature canon (64)
  { studio: "Disney", title: "Snow White and the Seven Dwarfs", year: 1937 },
  { studio: "Disney", title: "Pinocchio", year: 1940 },
  { studio: "Disney", title: "Fantasia", year: 1940 },
  { studio: "Disney", title: "Dumbo", year: 1941 },
  { studio: "Disney", title: "Bambi", year: 1942 },
  { studio: "Disney", title: "Saludos Amigos", year: 1942 },
  { studio: "Disney", title: "The Three Caballeros", year: 1944 },
  { studio: "Disney", title: "Make Mine Music", year: 1946 },
  { studio: "Disney", title: "Fun and Fancy Free", year: 1947 },
  { studio: "Disney", title: "Melody Time", year: 1948 },
  { studio: "Disney", title: "The Adventures of Ichabod and Mr. Toad", year: 1949 },
  { studio: "Disney", title: "Cinderella", year: 1950 },
  { studio: "Disney", title: "Alice in Wonderland", year: 1951 },
  { studio: "Disney", title: "Peter Pan", year: 1953 },
  { studio: "Disney", title: "Lady and the Tramp", year: 1955 },
  { studio: "Disney", title: "Sleeping Beauty", year: 1959 },
  { studio: "Disney", title: "One Hundred and One Dalmatians", year: 1961, aliases: ["101 Dalmatians"] },
  { studio: "Disney", title: "The Sword in the Stone", year: 1963 },
  { studio: "Disney", title: "The Jungle Book", year: 1967 },
  { studio: "Disney", title: "The Aristocats", year: 1970 },
  { studio: "Disney", title: "Robin Hood", year: 1973 },
  { studio: "Disney", title: "The Many Adventures of Winnie the Pooh", year: 1977 },
  { studio: "Disney", title: "The Rescuers", year: 1977 },
  { studio: "Disney", title: "The Fox and the Hound", year: 1981 },
  { studio: "Disney", title: "The Black Cauldron", year: 1985 },
  { studio: "Disney", title: "The Great Mouse Detective", year: 1986 },
  { studio: "Disney", title: "Oliver & Company", year: 1988 },
  { studio: "Disney", title: "The Little Mermaid", year: 1989 },
  { studio: "Disney", title: "The Rescuers Down Under", year: 1990 },
  { studio: "Disney", title: "Beauty and the Beast", year: 1991 },
  { studio: "Disney", title: "Aladdin", year: 1992 },
  { studio: "Disney", title: "The Lion King", year: 1994 },
  { studio: "Disney", title: "Pocahontas", year: 1995 },
  { studio: "Disney", title: "The Hunchback of Notre Dame", year: 1996 },
  { studio: "Disney", title: "Hercules", year: 1997 },
  { studio: "Disney", title: "Mulan", year: 1998 },
  { studio: "Disney", title: "Tarzan", year: 1999 },
  { studio: "Disney", title: "Fantasia 2000", year: 1999 },
  { studio: "Disney", title: "Dinosaur", year: 2000 },
  { studio: "Disney", title: "The Emperor's New Groove", year: 2000 },
  { studio: "Disney", title: "Atlantis: The Lost Empire", year: 2001 },
  { studio: "Disney", title: "Lilo & Stitch", year: 2002 },
  { studio: "Disney", title: "Treasure Planet", year: 2002 },
  { studio: "Disney", title: "Brother Bear", year: 2003 },
  { studio: "Disney", title: "Home on the Range", year: 2004 },
  { studio: "Disney", title: "Chicken Little", year: 2005 },
  { studio: "Disney", title: "Meet the Robinsons", year: 2007 },
  { studio: "Disney", title: "Bolt", year: 2008 },
  { studio: "Disney", title: "The Princess and the Frog", year: 2009 },
  { studio: "Disney", title: "Tangled", year: 2010 },
  { studio: "Disney", title: "Winnie the Pooh", year: 2011 },
  { studio: "Disney", title: "Wreck-It Ralph", year: 2012 },
  { studio: "Disney", title: "Frozen", year: 2013 },
  { studio: "Disney", title: "Big Hero 6", year: 2014 },
  { studio: "Disney", title: "Zootopia", year: 2016 },
  { studio: "Disney", title: "Moana", year: 2016 },
  { studio: "Disney", title: "Ralph Breaks the Internet", year: 2018 },
  { studio: "Disney", title: "Frozen II", year: 2019, aliases: ["Frozen 2"] },
  { studio: "Disney", title: "Raya and the Last Dragon", year: 2021 },
  { studio: "Disney", title: "Encanto", year: 2021 },
  { studio: "Disney", title: "Strange World", year: 2022 },
  { studio: "Disney", title: "Wish", year: 2023 },
  { studio: "Disney", title: "Moana 2", year: 2024 },
  { studio: "Disney", title: "Zootopia 2", year: 2025 },

  // Pixar Animation Studios — released features (31)
  { studio: "Pixar", title: "Toy Story", year: 1995 },
  { studio: "Pixar", title: "A Bug's Life", year: 1998 },
  { studio: "Pixar", title: "Toy Story 2", year: 1999 },
  { studio: "Pixar", title: "Monsters, Inc.", year: 2001, aliases: ["Monsters Inc"] },
  { studio: "Pixar", title: "Finding Nemo", year: 2003 },
  { studio: "Pixar", title: "The Incredibles", year: 2004 },
  { studio: "Pixar", title: "Cars", year: 2006 },
  { studio: "Pixar", title: "Ratatouille", year: 2007 },
  { studio: "Pixar", title: "WALL-E", year: 2008, aliases: ["WALL·E"] },
  { studio: "Pixar", title: "Up", year: 2009 },
  { studio: "Pixar", title: "Toy Story 3", year: 2010 },
  { studio: "Pixar", title: "Cars 2", year: 2011 },
  { studio: "Pixar", title: "Brave", year: 2012 },
  { studio: "Pixar", title: "Monsters University", year: 2013 },
  { studio: "Pixar", title: "Inside Out", year: 2015 },
  { studio: "Pixar", title: "The Good Dinosaur", year: 2015 },
  { studio: "Pixar", title: "Finding Dory", year: 2016 },
  { studio: "Pixar", title: "Cars 3", year: 2017 },
  { studio: "Pixar", title: "Coco", year: 2017 },
  { studio: "Pixar", title: "Incredibles 2", year: 2018 },
  { studio: "Pixar", title: "Toy Story 4", year: 2019 },
  { studio: "Pixar", title: "Onward", year: 2020 },
  { studio: "Pixar", title: "Soul", year: 2020 },
  { studio: "Pixar", title: "Luca", year: 2021 },
  { studio: "Pixar", title: "Turning Red", year: 2022 },
  { studio: "Pixar", title: "Lightyear", year: 2022 },
  { studio: "Pixar", title: "Elemental", year: 2023 },
  { studio: "Pixar", title: "Inside Out 2", year: 2024 },
  { studio: "Pixar", title: "Elio", year: 2025 },
  { studio: "Pixar", title: "Hoppers", year: 2026 },
  { studio: "Pixar", title: "Toy Story 5", year: 2026 }
];
